### ISSUE TITLE
Bias towards the first endpoints

### ISSUE THREAD

**Issue by np** [haskell-servant/servant-quickcheck#18]
The `HasGenRequest` instance for `:<|>` is nice and simple but leads to an unsatisfactory bias.

This can be demonstrated with the following snippet:

```
λ> map length . group . sort <$> sequence (replicate 100 (generate (oneof [pure 1, pure 2, pure 3])))
[33,30,37]
λ> map length . group . sort <$> sequence (replicate 100 (generate (oneof [pure 1, oneof [pure 2, pure 3]])))
[54,20,26]
```

It would be nice if alternatives where _effectively_ associatives.

**Comment by jkarni** [comment]
Good catch! Also, neat way of testing it!

I wrote a quick solution in #19, though I still need to fix a test and add one that checks that this behavior is indeed fixed.
