### ISSUE TITLE
servant doesn't satisfy notAllowedContainsAllowHeader

### ISSUE THREAD

**Issue by jml** [haskell-servant/servant-quickcheck#21]
I tried servant-quickcheck on a really simple servant API, but it failed `notAllowedContainsAllowHeader`. I was surprised, since servant theoretically has all the information it needs to be able to provide a meaningful response there. Further, it's not at all clear what I'd have to do to satisfy it.

**Comment by jkarni** [comment]
Thanks for the report. I opened an [issue](https://github.com/haskell-servant/servant/issues/489) on the `servant` repo about this some time back, but haven't yet gotten around to fixing it (you're right that servant has all the information to do this). 

Perhaps in the meantime the `servant-quickcheck` documentation should point out that `servant` itself doesn't implement this?

**Comment by jml** [comment]
Yeah, I think that would be a good step forward. A slightly better one might be a pointer to how to implement this with your own servant api (i.e. without modifying servant itself), but I feel that's just make-work.

**Comment by jkarni** [comment]
I added the note to the docs. 

Fixing it in `servant` would be *easier* as in one's own code, and would only have to be done once, so I don't think describing how to do this yourself is a good idea.
