### ISSUE TITLE
Confusion on OnlyJsonObjects predicate

### ISSUE THREAD

**Issue by Superpat** [haskell-servant/servant-quickcheck#31]
So I'm using the library to check my servant api, but the tests are failing on the onlyjsonobjects predicate and I'm confused as to why.
```
data User' login pwd email first last id = User
                         { userLogin     :: login
                         , userPassword  :: pwd
                         , userEmail     :: email
                         , userFirstName :: first
                         , userLastName  :: last
                         , userId        :: id
                         } deriving (Eq, Show, Generic)

type UserRead = User' Text ByteString Text Text Text UserId

instance ToJSON UserRead where
  toJSON user = object [ "userLogin" .= userLogin user
                       , "userEmail" .= userEmail user
                       , "userFirstName" .= userFirstName user
                       , "userLastName" .= userLastName user
                       , "userId" .= userId user
                       ]

type UserAPI = Get '[JSON] [UserRead]

userAPI :: Proxy UserAPI
userAPI = Proxy

userServer :: ServerT UserAPI AppM
userServer =
    getUsers

getUsers :: AppM [UserRead]
getUsers = do
    con <- getConn
    addToLogger "I got Users!"
    liftIO $ O.runQuery con usersQuery
```

The `"Content-Type": "application/json"` header is set and the body looks like this `Body: []`

There is nothing in my database right now, so the request should rightly send an empty list. I'm probably missing something obvious though.

**Comment by erewok** [comment]
Hi, @Superpat. Thanks for writing in and sorry it took us awhile to reply. 

The [`onlyJsonObjects` predicate](https://github.com/haskell-servant/servant-quickcheck/blob/master/src/Servant/QuickCheck/Internal/Predicates.hs#L93) tries to decode only `Object`s, which would not include top-level Arrays. 

It's possible that we could do one or all of the following:

1. Make the documentation on `onlyJsonObjects` clearer or more available.
2. Offer a more lax predicate, something like `isValidJson`, which tries to decode either an `Object` or top-level `Array`.

There is some controversy, though, on top-level arrays, as noted in the [current documentation](https://hackage.haskell.org/package/servant-quickcheck-0.0.2.4/docs/Servant-QuickCheck-Internal-Predicates.html):

> Best Practice
> Returning anything other than an object when returning JSON is considered bad practice, as:
> 
> 1. it is hard to modify the returned value while maintaining backwards compatibility
> 2. many older tools do not support top-level arrays
> 3. whether top-level numbers, booleans, or strings are valid JSON depends on what RFC you're going by
> 4. there are security issues with top-level arrays
>
> This function checks that any application/json responses only return JSON objects (and not arrays, strings, numbers, or booleans) at the top level.
>

**Comment by jkarni** [comment]
@Superpat does Erik's answer suffice? Can this be closed?
