### ISSUE TITLE
0.0.4 Hackage release?

### ISSUE THREAD

**Issue by adinapoli-iohk** [haskell-servant/servant-quickcheck#39]
Hey folks!

Considering that @phadej already put the work it to make this work with Servant 0.12, what's preventing it to land on Hackage? 😉 

Thanks a ton!

**Comment by phadej** [comment]
See #38

**Comment by adinapoli-iohk** [comment]
@phadej Ouch!

**Comment by qrilka** [comment]
There's already `0.0.7.0` on Hackage - probably time to close this one? :)
