### ISSUE TITLE
Add servant-quickcheck to stackage

### ISSUE THREAD

**Issue by Phenitei** [haskell-servant/servant-quickcheck#54]
`servant-quickcheck` is not currently in any stackage snapshot. It would be nice if that could be changed, as it would simplify it's usage in projects using stack.

**Comment by alpmestan** [comment]
Feel free to add it if you'd like to see it there, I don't think the person adding a package has to be a maintainer of the said package, right?

**Comment by Phenitei** [comment]
Not sure about the adding / maintaining thing. I'll check that, add it if it's possible and come back here otherwise.

**Comment by parsonsmatt** [comment]
[PR up here](https://github.com/commercialhaskell/stackage/pull/3922) :)

**Comment by Phenitei** [comment]
Fantastic! Thanks :)

**Comment by Phenitei** [comment]
I can confirm it's done, thanks again!
