### ISSUE TITLE
Hackage revision for base-4.12.0.0

### ISSUE THREAD

**Issue by jkachmar** [haskell-servant/servant-quickcheck#60]
It looks like this repository was updated to support `base-4.12.0.0`, but Hackage hasn't been updated with a revision reflecting this.

If someone could publish such a revision, we can get `servant-quickcheck` into the latest Stackage nightly.

**Comment by parsonsmatt** [comment]
We've uploaded a new version `0.0.7.3` which has support for GHC 8.6. Thanks!

**Comment by phadej** [comment]
Thanks
