### ISSUE TITLE
Support for servant 15

### ISSUE THREAD

**Issue by Phenitei** [haskell-servant/servant-quickcheck#64]
Hi,

There is no version of servant-quickcheck that supports servant 15, which is the version of the latest stackage LTS. In servant-quickcheck 7.4, the minimum version is 16, but in 7.3 the maximum version is 14.

Is the code in 7.4 compatible with servant 15, in which case one could just put `allow-newer: true` in the stack.yaml until 16 becomes the LTS, or have there been breaking changes ?

(And as a side-note, there is no changelog for the 7.4 version)

Best,

**Comment by fizruk** [comment]
@Phenitei as a workaround you can use this in your `extra-deps` or custom snapshots:

```yaml
- git: 'https://github.com/fizruk/servant-quickcheck.git'
  commit: bb8177928ef40806b1a9a82090b4a1a973c9cf93 # support servant-0.15
```

**Comment by Phenitei** [comment]
@fizruk Thanks! I'll keep an eye on #65 as well.
